// <auto-generated />
namespace Webserver.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EntityCleanup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntityCleanup));
        
        string IMigrationMetadata.Id
        {
            get { return "201912041822106_EntityCleanup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
